### ISSUE TITLE
Can measurement  frequency response of mobile loudspeaker 

### ISSUE THREAD

**Issue by zuowanbushiwo** [mbrennwa/mataa#12]
Dear Sir
this is a really cool project，I want to use the measured mobile (like Huawei Mate, iPhone , Samsung and smartspeaker and laptop ) loudspeaker impulse response (Not include Room impulse response) ,    Can this project do this ?
thanks！

**Comment by mbrennwa** [comment]
That should be possible you can configure the computer to feed the test signal into the mobile. I have no experience with this, but I guess there might be a way to configure the computer to use the mobile as a sound output device.

**Comment by zuowanbushiwo** [comment]
@mbrennwa 
Thank you very much for your reply
Can I use it offline , like this 
1. I use mataa to generate the audio to be played . 
2. I play the audio and record it on a mobile 
3. then use mataa to analyze the audio played and recorded on the mobile , and calculate  loudspeaker impulse response

I still have a big question, measurement a  loudspeaker impulse response (Not include Room impulse response)  have to be done in an anechoic room? Can it be done in an ordinary room? For example, a 10m X 5m X 3.5m room with very few things placed in it.

Thank you for your time and consideration.
Best regards,

**Comment by mbrennwa** [comment]
Yes, 1-2-3 works. Just use the mataa tools as described in the documentation.

Getting anechoic data from impulse response is usually straight forward, but the basic concepts are not specific to mataa. I'd recommend to read up on this elsewhere.
