### ISSUE TITLE
Issue running RC high-pass filter

### ISSUE THREAD

**Issue by indyucoder** [mbrennwa/mataa#2]
Just starting with the example RC high-pass filter...

>> w = mataa_signal_generator('white',96000,0.3);
>> h = mataa_measure_IR(w,96000);
Creating / resetting to MATAA default settings (command: save -mat .\.mataa_settings.mat mataa_settings ; )...

  scalar structure containing the fields:

    plotColor = b
    plotWindow_IR =  1
    plotWindow_SR =  2
    plotWindow_FR =  3
    plotWindow_CSD =  4
    plotWindow_ETC =  5
    plotWindow_HD =  6
    plotWindow_impedance =  7
    plotWindow_TBES =  8
    openPlotAfterSafe =  1
    channel_DUT =  1
    channel_REF =  2
    interchannel_delay = 0
...done.
error: 'latency' undefined near line 73 column 67
error: evaluating argument list element number 3
error: called from:
error:   C:/Users/findelic/Desktop/mataa-User/mataa_tools\mataa_measure_IR.m at line 73, column 18

**Comment by mbrennwa** [comment]
What do you get from the mataa selftest (see manual)?

Am 31.07.2017 11:29 vorm. schrieb "indyucoder" <notifications@github.com>:

**Comment by indyucoder** [comment]
mataa_selftest
****** MATAA self test ******
You are running Octave version 4.0.3.
The computer platform is LINUX_X86-32.
MATAA main path is /home/fabio/OCTAVE/mataa/.
Files and directories in the MATAA main path:
.              LICENSE.txt    TestTone       documentation  mataa_tools
..             README.txt     calibration    mataa_scripts  test_signals
MATAA test-signals path is /home/fabio/OCTAVE/mataa/test_signals/.
MATAA tools path is /home/fabio/OCTAVE/mataa/mataa_tools/.
MATAA TestTone path is /home/fabio/OCTAVE/mataa/TestTone/LINUX_X86-32/.
MATAA scripts path is /home/fabio/OCTAVE/mataa/mataa_scripts/.
MATAA path to calibration data is /home/fabio/OCTAVE/mataa/calibration/.
Your MATAA tools are (files and directories in the MATAA tools path):
.                                  mataa_phase_remove_trend.m
..                                 mataa_plot_CSDt.m
mataa_FR_extend_LF.m               mataa_plot_ETC_dB.m
mataa_FR_smooth.m                  mataa_plot_ETC_lin.m
mataa_IR_demo.m                    mataa_plot_FR.m
mataa_IR_remove_echo.m             mataa_plot_HD.m
mataa_IR_to_CSD.m                  mataa_plot_IR.m
mataa_IR_to_ETC.m                  mataa_plot_SR.m
mataa_IR_to_FR.m                   mataa_plot_TBESf.m
mataa_IR_to_FR_LFextend.m          mataa_plot_defaults.m
mataa_IR_to_SR.m                   mataa_plot_impedance.m
mataa_IR_to_TBES.m                 mataa_plot_one.m
mataa_audio_guess_latency.m        mataa_plot_save.m
mataa_audio_info.m                 mataa_plot_time_signal.m
mataa_computer.m                   mataa_plot_two.m
mataa_convolve.m                   mataa_plot_two_logX.m
mataa_deConvolve.m                 mataa_realFT.m
mataa_export_FRD.m                 mataa_realFT0.m
mataa_export_TMD.m                 mataa_realIFT.m
mataa_f_to_t.m                     mataa_realIFT0.m
mataa_file_default_name.m          mataa_running_mean.m
mataa_gnuplot.m                    mataa_select_signal_window_time.m
mataa_guess_IR_start.m             mataa_settings.m
mataa_hilbert.m                    mataa_signal_analytic.m
mataa_impedance_fit_speaker.m      mataa_signal_autocorr.m
mataa_impedance_speaker_model.m    mataa_signal_calibrate.m
mataa_import_AIFF.m                mataa_signal_clipcheck.m
mataa_import_FRD.m                 mataa_signal_crop.m
mataa_import_TMD.m                 mataa_signal_generator.m
mataa_import_mlssa.m               mataa_signal_pad_Zeros.m
mataa_interp.m                     mataa_signal_removeHF.m
mataa_load_calibration.m           mataa_signal_save.m
mataa_measure_IR.m                 mataa_signal_spectrogram.m
mataa_measure_impedance.m          mataa_signal_to_TestToneFile.m
mataa_measure_signal_response.m    mataa_signal_window.m
mataa_measure_sine_distortion.m    mataa_smooth_log.m
mataa_menu.m                       mataa_t_to_f.m
mataa_minimum_phase.m              mataa_t_to_f0.m
mataa_octave_version.m             mataa_tempfile.m
mataa_path.m                       obsolete
mataa_phase_remove_delay.m
Your MATAA scripts are (files and directories in the MATAA scripts path):
.                         mataa_demo_loudspeaker.m
..                        mataa_selftest.m
Testing sound input/output...
  The audio device that will be used for audio output is: HDA ATI SB: AD1981 Analog (hw:0,0)
  The audio host API is (output): ALSA
     Number of channels of output device: 2
     Minimum sampling rate (sound output): 8000 Hz
     Maximum sampling rate (sound output): 48000 Hz
  The audio device that will be used for audio input is: HDA ATI SB: AD1981 Analog (hw:0,0)
  The audio host API is (input): ALSA
     Number of channels of input device: 2
     Minimum sampling rate (sound input): 8000 Hz
     Maximum sampling rate (sound input): 48000 Hz
  The audio I/O test will be done using a sine-wave signal with:
     frequency = 1000 Hz
     duration = 0.100000 s
     sampling rate = 44100 Hz
  Starting sound I/O...
warning: mataa_measure_signal_response: latency (0s) is less than generic default (0.1s). Make sure this is really what you want and check for truncated data!
Writing sound data to disk...
...done
Sound input / output started...
Sound output device: HDA ATI SB: AD1981 Analog (hw:0,0)
Sound input device: HDA ATI SB: AD1981 Analog (hw:0,0)
Sampling rate: 44.100 kHz
...sound I/O done.
Reading sound data from disk...
...data reading done.
Max amplitude in channel 1 (DUT): 67.1%
Max amplitude in channel 2 (REF): 63.8%
No calibration data available. Returning raw, uncalibrated data!
   ...sound input/output done.
   You may have noticed a short beep at the output of your sound output device.
   The max. amplitude of the input signal in channel 1 is 67%
   The max. amplitude of the input signal in channel 2 is 64%
   (these values will depend on the setup of your audio device(s) and the the connections to it.)
...testing of sound input/output completed.
****** MATAA self test completed ******

**Comment by mbrennwa** [comment]
Your audio interface is not compatible with 96k.

Am 01.08.2017 4:25 nachm. schrieb "indyucoder" <notifications@github.com>:

**Comment by indyucoder** [comment]
My fault, I've cut&paste from mataa readable pdf ... here the full copy from Octave prompt ...
 
 w = mataa_signal_generator('white',44100,0.3);
 plot(w(:,1))
 h = mataa_measure_IR (w,44100);
error: 'latency' undefined near line 73 column 67
error: called from
    mataa_measure_IR at line 73 column 18
error: evaluating argument list element number 3
error: called from
    mataa_measure_IR at line 73 column 18

**Comment by mbrennwa** [comment]
Okay, try to explicitly specify a latency value in the measure_IR call.

Am 01.08.2017 5:42 nachm. schrieb "indyucoder" <notifications@github.com>:

My fault, I've cut&paste from mataa readable pdf ... here the full copy
from Octave prompt ...

w = mataa_signal_generator('white',44100,0.3);
plot(w(:,1))
h = mataa_measure_IR (w,44100);

error: 'latency' undefined near line 73 column 67
error: called from
mataa_measure_IR at line 73 column 18

error: evaluating argument list element number 3
error: called from
mataa_measure_IR at line 73 column 18

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mbrennwa/mataa/issues/2#issuecomment-319410094>, or mute
the thread

**Comment by indyucoder** [comment]
Added N=1  and latency=0.1

Now working :)

Thx 

h = mataa_measure_IR (w,44100,1,0.1);
Writing sound data to disk...
...done
Sound input / output started...
Sound output device: HDA ATI SB: AD1981 Analog (hw:0,0)
Sound input device: HDA ATI SB: AD1981 Analog (hw:0,0)
Sampling rate: 44.100 kHz
...sound I/O done.
Reading sound data from disk...
...data reading done.
Max amplitude in channel 1 (DUT): 88.9%
No calibration data available. Returning raw, uncalibrated data!
Deconvolving data using raw test signal as reference (no loopback data available)...
...deconvolution done.
