### ISSUE TITLE
Issues running with Matlab R2018b (9.5.0.944444)

### ISSUE THREAD

**Issue by nickpourazima** [mbrennwa/mataa#5]
Error: File: mataa_measure_signal_response.m
Line: 355 Column: 50 
Incorrect use of '=' operator. 
To assign a value to a variable, use '='. 
To compare values for equality, use '=='.

https://github.com/mbrennwa/mataa/blob/4c8f5f8ac7aa151c7282b836224e2643fbaee999/mataa_tools/mataa_measure_signal_response.m#L355

solved by changing to:

        dut_in_unit{k} = '???';
        dut_out_unit{k} = '???';

**Comment by nickpourazima** [comment]
Error: File: mataa_cal_autoscale.m 
Line: 39 Column: 27
Incorrect use of '=' operator. 
To assign a value to a variable, use '='. 
To compare values for equality, use '=='.

solved by changing to:
```
cal_adc = [];
cal_dac = [];
```

**Comment by nickpourazima** [comment]
Undefined function or variable 'toupper'.
Error in mataa_measure_signal_response (line 186)
`if strcmp (toupper(X0_unit),'DIGITAL') % no amplitude conversion`

solved by changing to:

`if strcmp (upper(X0_unit),'DIGITAL') % no amplitude conversion`

**Comment by nickpourazima** [comment]
Undefined function or variable 'stdout'.

Error in mataa_measure_signal_response (line 387)
`fflush (stdout);`

solved by changing to:

`drawnow('limitrate');`

**Comment by nickpourazima** [comment]
### Unresolved
Error using interp1>parseinputs (line 363)
An interpolation method must be specified with 'extrap'.

Error in interp1 (line 78)
[method,extrapval,ndataarg,pp] = parseinputs(varargin{:});

Error in mataa_FR_smooth (line 61)
	mag   = interp1 (f0,mag,f,'extrap');

**Comment by mbrennwa** [comment]
I have revised the code so it should avoid the Matlab issues described above. However, I cannot test the revision because I don't have access to Matlab. Please check and let me know.
