### ISSUE TITLE
compile warnings, format specifier 

### ISSUE THREAD

**Issue by WrickColl** [mbrennwa/mataa#6]
When compiling TestTonePA19.c as per the instructions in the README, I get warnings on lines:
279, 286, 373, and 383 saying tht format %d expects an int but gets an long unsigned int.

The format for all four should be changed to %lu
 
Compiling TestDevicesPA19.c I get warnings on lines 140 and 175, too many arguments for format
both printf statements need to be fixed.

**Comment by mbrennwa** [comment]
Thanks for your report.

I believe both suggestions make sense. However, before changing anything, I'd like to understand why these issues did not appear earlier. I am not very experienced with C and compilers. Any ideas?

**Comment by WrickColl** [comment]
Possibly the type of the variables in question have been updated from 
int to long unsigned int in an included header file since you last 
compiled TestTone.

Another thought, maybe you have turned off warnings when you compile.

Although, the printf with too many parameters should have been an issue 
for you when you compiled that file. So that's a mystery to me.

Sorry I'm not of much more help.

**Comment by mbrennwa** [comment]
I fixed the code as suggested. I don't get any warnings from the compiler now.
