### ISSUE TITLE
ld cannot find -lasound

### ISSUE THREAD

**Issue by WrickColl** [mbrennwa/mataa#7]
This error occurs when compiling TestTonePA19.c and  TestDevicePA19.c per the instructions in the README
gcc -lrt -lasound -lpthread -o TestTonePA19 TestTonePA19.c libportaudio.a
...
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status

Are there other files I need to copy from elsewhere, or paths I need to define?

Note this is regardless of the printf format warnings mentioned in my other issue.
I am using Ubuntu 18.10 in a VM on Windows 10.
and using freshly downloaded MATAA and portaudio files.
I am following the README as written (i.e. with no assumptions made by me.)

**Comment by mbrennwa** [comment]
This looks like you need to install the dev part of libasound. Maybe try installing this: https://packages.ubuntu.com/search?keywords=libasound2-dev

Why do you need to compile things from scratch? You should be able to just use the precompiled versions of TestTone and TestDevices on your Ubuntu machine. Did you try running mataa_selftest as described in section 2.7 of the manual?

**Comment by WrickColl** [comment]
Thank you for your prompt and informative reply.

Um, well, yes, actually I didn't need to do this. I was trying to rush 
things and when I read "to compile ... do ..." I just did without 
thinking. I glossed over the "If you need " (to compile...) part.

But perhaps you could add advice to the README.

**Comment by mbrennwa** [comment]
I added this to the README describing how to compile TestTone and TestDevices for Linux.
